export default [
  {
    nome: "Tênis Mizuno Space 4 Feminino",
    image: "https://imgcentauro-a.akamaihd.net/768x768/98650812.jpg",
    qualidades: "Bege",
    preco: "R$279,99",
    descricao: "O Tênis Mizuno Space 4 é uma escolha ideal para os corredores que buscam desempenho e estilo. Com um design arrojado e estrutura proporcionada pelo tecido mesh e cabedal injetado, este tênis oferece suporte e conforto durante as corridas. Indicado especificamente para corrida, o Mizuno Space 4 possui um drop de 9mm e é parte da linha Running da marca, garantindo que atenda às necessidades dos corredores neutros. Seu fechamento em cadarço permite um ajuste personalizado. Fabricado nacionalmente, este tênis Mizuno vem com garantia do fabricante contra defeitos de fabricação, proporcionando tranquilidade aos corredores quanto à qualidade do produto. Com o Mizuno Space 4, os corredores podem desfrutar de conforto, suporte e estilo em suas corridas, alcançando seus objetivos com confiança.",
    id: 1,
  },

  {
    nome: "Tênis Nike Revolution 7 - Masculino",
    image: " https://imgcentauro-a.akamaihd.net/768x768/985824K5.jpg",
    qualidades: "Azul/azul claro",
    preco: "R$ 279,99",
    descricao: "Desenvolvido para proporcionar uma experiência única, este tênis combina tecnologia de ponta com um design moderno que eleva seu estilo durante os treinos e corridas. O amortecimento responsivo presente no Revolution 7 garante um conforto incomparável a cada impacto, permitindo que você ultrapasse seus limites com confiança.",
    id: 2,
  },
  
  {
    nome: "Tênis Mizuno Enigma Masculino",
    image: "https://imgcentauro-a.akamaihd.net/768x768/98651102.jpg",
    qualidades: "Preto",
    preco: "R$ 359,99",
    descricao: "Foi desenvolvido para oferecer conforto e performance em suas atividades físicas. A parte superior em mesh proporciona respirabilidade e um ajuste confortável. A entressola em EVA com tecnologia SoftierFoam garante excelente amortecimento e suavidade a cada passo.",
    id: 3,
  },
  {
    nome: "Tênis Olympikus Corre 3 - Unissex",
    image: "https://imgcentauro-a.akamaihd.net/768x768/98009511.jpg",
    qualidades: "Laranja",
    preco: "R$ 359,99",
    descricao: "Com o tênis Olympikus Corre 3, você terá uma experiência de corrida jamais vista. Um calçado que alinha tecnologia e muito conforto. Ele foi desenvolvido em colaboração com especialistas em corrida e submetido a rigorosos testes no Laboratório de Biomecânica da USP.",
    id: 4,
  },
  {
    nome: "Tênis Mizuno Cool Ride - Feminino",
    image: "https://imgcentauro-a.akamaihd.net/768x768/970090KR.jpg",
    qualidades: "Branco",
    preco: "R$ 429,99",
    descricao: "Produzido em tecido knit e conta com cabedal no estilo meia para maior conforto e praticidade no ajuste e calce. Seu solado em EVA com regiões de borracha garante maior aderência e durabilidade ao modelo. Tudo isso sem perder o conforto, a leveza e a flexibilidade.",
    id: 5,
  },
  {
    nome: "Tênis Nike Revolution 7 Juvenil",
    image: "https://static.netshoes.com.br/produtos/tenis-nike-revolution-7-juvenil/18/JD8-6365-018/JD8-6365-018_zoom1.jpg?ts=1708335838?ims=1088x",
    qualidades: "Rosa",
    preco: "R$ 219,99",
    descricao: "O Revolution 7 vem em cores incríveis e designs que vão fazer as crianças quererem usá-lo todos os dias do ano.O colarinho é super macio, tão confortável que você pode confundi-lo com um travesseiro em volta do tornozelo. Além disso, a almofada no calcanhar proporciona conforto extra.",
    id: 6,
  },
  {
    nome: "Tênis adidas Lite Racer 3.0 - Masculino",
    image: "https://imgcentauro-a.akamaihd.net/768x768/98349403.jpg",
    qualidades: "Cinza",
    preco: "R$ 360,99",
    descricao: "garante conforto aos pés, desempenho e previne lesões pelo impacto ao usuário. Além disso, é de peso leve e com excelente custo-benefício, ideal para corredores que buscam uma combinação entre a versatilidade e tecnologia de amortecimento.",
    id: 7,
  },
  {
    nome: "Tênis Nike In-Season TR 13 Feminino",
    image: "https://static.netshoes.com.br/produtos/tenis-nike-in-season-tr-13-feminino/14/JD8-5710-014/JD8-5710-014_zoom1.jpg?ts=1698436182?ims=400x",
    qualidades: "Branco",
    preco: "R$ 199,99",
    descricao: "Combinamos a entressola macia com uma plataforma estável que permite movimentos laterais e corridas curtas. Mais Benefícios Colarinho confortável oferece sensação macia e suporte, ajudando você a calçar e tirar o tênis com facilidade quando estiver em movimento. Antepé respirável com mesh de performance ajuda a manter você fresco.",
    id: 8,
  },
  {
    nome: "Tênis Converse All Star CT AS Core OX CT0001",
    image: "https://imgcentauro-a.akamaihd.net/768x768/88286801.jpg",
    qualidades: "Bege",
    preco: "R$ 499,99",
    descricao: "Modelo tradicional da marca, produzido em tecido canvas (algodão 100% resistente). Possui forro em tecido, sola e entressola emborrachadas, palmilha macia removível em EVA, para facilitar a limpeza, aplique da marca no calcanhar e na lingueta, fechamento em cadarço simétrico para melhor ajuste.",
    id: 9,
  },
  {
    nome: "Tênis Nike In-Season TR 13 Feminino",
    image: "https://imgcentauro-a.akamaihd.net/768x768/983515NMA1.jpg",
    qualidades: "Branco",
    preco: "R$ 360,99",
    descricao: "Combinamos a entressola macia com uma plataforma estável que permite movimentos laterais e corridas curtas. Mais Benefícios Colarinho confortável oferece sensação macia e suporte, ajudando você a calçar e tirar o tênis com facilidade quando estiver em movimento. Antepé respirável com mesh de performance ajuda a manter você fresco.",
    id: 10,
  },
  {
    nome: "Tênis Nike In-Season TR 13 Feminino",
    image: "https://imgcentauro-a.akamaihd.net/768x768/983515NMA1.jpg",
    qualidades: "Rosa claro",
    preco: "R$ 199,99",
    descricao: "Combinamos a entressola macia com uma plataforma estável que permite movimentos laterais e corridas curtas. Mais Benefícios Colarinho confortável oferece sensação macia e suporte, ajudando você a calçar e tirar o tênis com facilidade quando estiver em movimento. Antepé respirável com mesh de performance ajuda a manter você fresco.",
    id: 11,
  },
  {
    nome: "Tênis Nike In-Season TR 13 Feminino",
    image: "https://static.netshoes.com.br/produtos/tenis-nike-in-season-tr-13-feminino/14/JD8-5710-014/JD8-5710-014_zoom1.jpg?ts=1698436182?ims=400x",
    qualidades: "Branco",
    preco: "R$ 360,99",
    descricao: "Combinamos a entressola macia com uma plataforma estável que permite movimentos laterais e corridas curtas. Mais Benefícios Colarinho confortável oferece sensação macia e suporte, ajudando você a calçar e tirar o tênis com facilidade quando estiver em movimento. Antepé respirável com mesh de performance ajuda a manter você fresco.",
    id: 12,
  },
  {
    nome: "Tênis Nike In-Season TR 13 Feminino",
    image: "https://static.netshoes.com.br/produtos/tenis-nike-in-season-tr-13-feminino/14/JD8-5710-014/JD8-5710-014_zoom1.jpg?ts=1698436182?ims=400x",
    qualidades: "Branco",
    preco: "R$ 360,99",
    descricao: "Combinamos a entressola macia com uma plataforma estável que permite movimentos laterais e corridas curtas. Mais Benefícios Colarinho confortável oferece sensação macia e suporte, ajudando você a calçar e tirar o tênis com facilidade quando estiver em movimento. Antepé respirável com mesh de performance ajuda a manter você fresco.",
    id: 13,
  },
  {
    nome: "Tênis Nike In-Season TR 13 Feminino",
    image: "https://static.netshoes.com.br/produtos/tenis-nike-in-season-tr-13-feminino/14/JD8-5710-014/JD8-5710-014_zoom1.jpg?ts=1698436182?ims=400x",
    qualidades: "Branco",
    preco: "R$ 360,99",
    descricao: "Combinamos a entressola macia com uma plataforma estável que permite movimentos laterais e corridas curtas. Mais Benefícios Colarinho confortável oferece sensação macia e suporte, ajudando você a calçar e tirar o tênis com facilidade quando estiver em movimento. Antepé respirável com mesh de performance ajuda a manter você fresco.",
    id: 14,
  },
  {
    nome: "Tênis Nike In-Season TR 13 Feminino",
    image: "https://static.netshoes.com.br/produtos/tenis-nike-in-season-tr-13-feminino/14/JD8-5710-014/JD8-5710-014_zoom1.jpg?ts=1698436182?ims=400x",
    qualidades: "Branco",
    preco: "R$ 360,99",
    descricao: "Combinamos a entressola macia com uma plataforma estável que permite movimentos laterais e corridas curtas. Mais Benefícios Colarinho confortável oferece sensação macia e suporte, ajudando você a calçar e tirar o tênis com facilidade quando estiver em movimento. Antepé respirável com mesh de performance ajuda a manter você fresco.",
    id: 15,
  },
  {
    nome: "Tênis Nike In-Season TR 13 Feminino",
    image: "https://static.netshoes.com.br/produtos/tenis-nike-in-season-tr-13-feminino/14/JD8-5710-014/JD8-5710-014_zoom1.jpg?ts=1698436182?ims=400x",
    qualidades: "Branco",
    preco: "R$ 360,99",
    descricao: "Combinamos a entressola macia com uma plataforma estável que permite movimentos laterais e corridas curtas. Mais Benefícios Colarinho confortável oferece sensação macia e suporte, ajudando você a calçar e tirar o tênis com facilidade quando estiver em movimento. Antepé respirável com mesh de performance ajuda a manter você fresco.",
    id: 16,
  },
];

